### ISSUE TITLE
relevanceMaps function needs to be parallelized.

### ISSUE THREAD

**Issue by ghost** [SantanderMetGroup/downscaleR.keras#3]
So I have a grid of 135x129 and I am using the relevanceMaps function for predictor difference analysis. I am using 15 predictors for analysis. However the function is taking around approximately 10 hours just for one iteration of one grid location. Therefore can you help me speed up this process. My email is deveshwarsingh90@gmail.com if you need any more specifics about the job.
 I have been using your amazing repos for years. Thanks in advance

**Comment by jorgebanomedina** [comment]
Hello,

Yes the function takes a lot of time due to the estimation of conditional probability functions. I recommend it to be used when your predictor and predictand's dimensions are not too high-dimensional (for instance, downscaling to station-scale). If this is not your case I would suggest you to use this other package about interpretability techniques (is coded in python but you can use the .h5 model infered with downscaleR.keras with python). 

https://github.com/albermax/innvestigate

Hope this helps,

Jorge
